// const fruits = [
//   { name: 'apple', age: "13", readyToEat: true },
//   { name: 'pear', age: 15, readyToEat: true },
//   { name: 'grapes', age: 1, readyToEat: false },
//   { name: 'kiwi', age: 2, readyToEat: true },
//   { name: 'dragon fruit', age: 88, readyToEat: false },
// ];

// module.exports = fruits;

//Example/structure of games database with names, age rating (E for everyone, T for teen, M for mature) and description of game.

const games = [
  { name: 'The Legend of Zelda: Breath of the Wild', agerating: "E", price: 30, description:"The Legend of Zelda: Breath of the Wild eschewed the semi-linear, borderline predictable path of the 3D Zelda games before it in favor of a bold, crazy new approach: let players do what they want, how they want, and in whatever order they decide. By marrying an open-ended approach to quest structure with the ability to freely explore a vast, beautiful, intriguing world with little specific regulation, the 3D Zelda game template was shattered about as fast as the average breakable weapon in Breath of the Wild. The result is a gorgeous, freeing open-world action/adventure experience that evokes the wonder and fear of exploring a bold new place with the empowering tangibility of becoming its hero. "  },
  { name: 'Portal 2', agerating: "E", price: 50, description:"Portal undoubtedly came out of nowhere and shattered the mold, but Portal 2 took that raw and incredible concept and managed to shape it into a more polished and impressive package. It cranked the dials up on just about everything that made the original so special. The mind-bending puzzles, the surprisingly dark story, and the ridiculous humor that balanced it out - each piece of that picture was refined and refreshed to build a sequel that actually surpassed the ambition of an already extremely ambitious game, making something both familiar and altogether new. It gave us a deeper look into the wonderful world of Aperture Science without completely dragging all of its mysteries out into the light. It also mixed its “thinking with portals” puzzles up even further by weaving in gel mechanics that felt entirely fresh and completely natural at the same time - while simultaneously and subtly using them to tie gameplay mechanics into the story, patiently waiting until its incredible finale to pay off those setups with one of the weirdest and most spectacular video game endings around. Couple that with a seriously good co-op campaign and even a full-on custom level builder and sharing systems added post-launch and Portal 2 has stayed the high bar by which all first-person puzzle games should be measured, even nearly a decade later. "  },
  { name: 'Super Mario World', agerating: "E", price: 40, description:"Super Mario World is a relatively simple game to describe. It’s a Super Mario game, and we all know what that means: Mushrooms; perfect running and jumping action; and a giant world to explore, crammed with secrets. But what sets Super Mario World apart from other 2D Mario games is its irresistible complexity. Subsequent Super Mario games, like the New Super Mario Bros. series, simplified the overworld, trading Super Mario World’s cool hidden paths for linear tracks, largely abandoned the skies and treetops of Super Mario World’s vertical levels for ground-based obstacle courses, and did away with flying almost entirely (capes rule, helicopter hats drool!). Super Mario World is the crescendo to the slow build in technology and game design that started with Super Mario Bros. Let Super Mario World’s placement on this list be a challenge to future game developers. We dare you to make a better game: Puzzling, but not opaque; tough but not intimidating; beautiful, funny, joyful, and universally recognizable. "  },
]

module.exports = games